import { basename } from "node:path";
import type { TemplateManifest } from "./manifest.ts";

/**
 * Pure generators: manifest -> deploy URLs / netlify.toml / .env.example /
 * docs buttons. No filesystem, no network — fully unit-testable. The CLI, the
 * repo codegen (`scripts/gen.ts`), and the docs build all call these.
 */

export interface RepoConfig {
  /** GitHub "owner/name" the templates live in. */
  githubRepo: string;
  branch: string;
  /** Docs link surfaced in deploy env-var prompts. */
  docsEnvLink: string;
  /** Default Model Match REST API base URL. */
  apiBaseUrl: string;
}

export const DEFAULT_REPO: RepoConfig = {
  githubRepo: "model-match-inc/examples",
  branch: "main",
  docsEnvLink: "https://docs.modelmatch.com/developers",
  apiBaseUrl: "https://api.modelmatch.com",
};

export function slugFor(m: TemplateManifest): string {
  return m.slug ?? basename(m.dir);
}

/** Non-secret vars that carry a default — safe to prefill in a URL. */
function envDefaults(m: TemplateManifest): Record<string, string> {
  const out: Record<string, string> = {};
  for (const v of m.variables) {
    if (!v.secret && v.default !== undefined) out[v.key] = v.default;
  }
  return out;
}

const FRAMEWORK_BUILD: Record<TemplateManifest["framework"], { command: string; publish: string }> = {
  vite: { command: "npm run build", publish: "dist" },
  "tanstack-start": { command: "npm run build", publish: "dist" },
  next: { command: "npm run build", publish: ".next" },
  node: { command: "npm run build", publish: "dist" },
};

/**
 * Vercel deploy-button URL. The monorepo subdir is encoded ENTIRELY in
 * `repository-url` as `/tree/<branch>/<dir>` — Vercel has no `root-directory`
 * query param, and adding one double-applies the path ("couldn't find the
 * source code"). Secrets are listed in `env` (deployer must fill them) but
 * never in `envDefaults` — the URL lands in browser history.
 */
export function vercelDeployUrl(m: TemplateManifest, repo: RepoConfig = DEFAULT_REPO): string {
  const url = new URL("https://vercel.com/new/clone");
  const p = url.searchParams;
  const slug = slugFor(m);
  p.set("repository-url", `https://github.com/${repo.githubRepo}/tree/${repo.branch}/${m.dir}`);
  p.set("project-name", `mm-${slug}`);
  p.set("repository-name", `mm-${slug}`);

  const keys = m.variables.map((v) => v.key);
  if (keys.length > 0) {
    p.set("env", keys.join(","));
    p.set("envDescription", `Configuration for ${m.name}`);
    p.set("envLink", repo.docsEnvLink);
    const defs = envDefaults(m);
    if (Object.keys(defs).length > 0) p.set("envDefaults", JSON.stringify(defs));
  }
  return url.toString();
}

/**
 * Netlify deploy-button URL. Netlify reads the variable spec from the repo's
 * `netlify.toml`; `create_from_path` clones only the subdir so its
 * `netlify.toml` lands at the cloned repo root (where `[template.environment]`
 * is honored — `base` is NOT).
 */
export function netlifyDeployUrl(m: TemplateManifest, repo: RepoConfig = DEFAULT_REPO): string {
  const url = new URL("https://app.netlify.com/start/deploy");
  url.searchParams.set("repository", `https://github.com/${repo.githubRepo}`);
  url.searchParams.set("create_from_path", m.dir);
  return url.toString();
}

/** The `netlify.toml` to commit into the template dir. */
export function netlifyToml(m: TemplateManifest): string {
  const b = { ...FRAMEWORK_BUILD[m.framework], ...(m.build ?? {}) };
  const lines: string[] = [
    "# Generated by @model-match/create — edit template.json then `npm run gen`.",
    "",
    "[build]",
    `  command = ${JSON.stringify(b.command)}`,
    `  publish = ${JSON.stringify(b.publish)}`,
  ];
  if (m.variables.length > 0) {
    lines.push("", "[template.environment]");
    for (const v of m.variables) {
      // Netlify uses the value as a UI label only; it can't set actual values.
      lines.push(`  ${v.key} = ${JSON.stringify(v.help ?? v.label)}`);
    }
  }
  return lines.join("\n") + "\n";
}

/** The `.env.example` to commit into the template dir. */
export function envExample(m: TemplateManifest): string {
  const lines: string[] = [
    `# ${m.name} — environment variables`,
    "# Generated by @model-match/create — edit template.json then `npm run gen`.",
  ];
  for (const v of m.variables) {
    lines.push("");
    for (const hl of (v.help ?? v.label).split("\n")) lines.push(`# ${hl}`);
    if (v.secret) lines.push("# (secret — never commit a real value)");
    lines.push(`${v.key}=${v.secret ? "replace-me" : v.default ?? "replace-me"}`);
  }
  return lines.join("\n") + "\n";
}

/** Markdown "Deploy" buttons for the docs site / README. */
export function docsButtonsMarkdown(m: TemplateManifest, repo: RepoConfig = DEFAULT_REPO): string {
  return [
    `[![Deploy with Vercel](https://vercel.com/button)](${vercelDeployUrl(m, repo)})`,
    `[![Deploy to Netlify](https://www.netlify.com/img/deploy/button.svg)](${netlifyDeployUrl(m, repo)})`,
  ].join("\n");
}

/** Serialize the discovered manifests into a module the CLI bundles. */
export function renderRegistryModule(templates: TemplateManifest[], repo: RepoConfig): string {
  return [
    "// AUTO-GENERATED by scripts/gen.ts — do not edit by hand.",
    'import type { TemplateManifest } from "./manifest.ts";',
    "",
    `export const REPO = ${JSON.stringify(repo, null, 2)} as const;`,
    "",
    `export const TEMPLATES: TemplateManifest[] = ${JSON.stringify(templates, null, 2)};`,
    "",
  ].join("\n");
}
