// AUTO-GENERATED by scripts/gen.ts — do not edit by hand.
import type { TemplateManifest } from "./manifest.ts";

export const REPO = {
  "githubRepo": "model-match-inc/examples",
  "branch": "main",
  "docsEnvLink": "https://docs.modelmatch.com/developers",
  "apiBaseUrl": "https://api.modelmatch.com"
} as const;

export const TEMPLATES: TemplateManifest[] = [
  {
    "name": "TanStack Start (confidential)",
    "slug": "tanstack-confidential",
    "description": "Authorization Code with a client_secret kept server-side. For apps that have a backend.",
    "framework": "tanstack-start",
    "auth": "oauth",
    "dir": "apps/tanstack-confidential",
    "build": {
      "publish": "dist"
    },
    "variables": [
      {
        "key": "MODEL_MATCH_ISSUER",
        "label": "OAuth issuer base URL",
        "help": "The SDK appends /oauth2/authorize and /oauth2/token to this value. Point it at the auth base, NOT the bare host (the bare host 404s — endpoints live under /api/auth).",
        "secret": false,
        "default": "https://auth.modelmatch.com/api/auth",
        "scope": "server"
      },
      {
        "key": "MMR_API_URL",
        "label": "Model Match REST API base URL",
        "secret": false,
        "default": "https://api.modelmatch.com",
        "scope": "server"
      },
      {
        "key": "MODEL_MATCH_CLIENT_ID",
        "label": "OAuth client ID",
        "secret": false,
        "scope": "server"
      },
      {
        "key": "MODEL_MATCH_CLIENT_SECRET",
        "label": "OAuth client secret",
        "help": "NEVER prefix this with VITE_ — it must never reach the browser bundle.",
        "secret": true,
        "scope": "server"
      },
      {
        "key": "MODEL_MATCH_REDIRECT_URI",
        "label": "OAuth redirect URI",
        "help": "Must exactly match the redirect URI registered with your OAuth app.",
        "secret": false,
        "default": "http://localhost:3000/oauth/callback",
        "scope": "server"
      }
    ]
  },
  {
    "name": "Vite SPA (PKCE)",
    "slug": "vite-spa-pkce",
    "description": "Public OAuth client using Authorization Code + PKCE. No secret — for browser/mobile/CLI apps.",
    "framework": "vite",
    "auth": "oauth",
    "dir": "apps/vite-spa-pkce",
    "variables": [
      {
        "key": "VITE_MODEL_MATCH_CLIENT_ID",
        "label": "OAuth client ID",
        "help": "A public OAuth client — there is NO secret. This value is inlined into the browser bundle, which is fine for a PKCE client.",
        "secret": false,
        "scope": "build"
      },
      {
        "key": "VITE_MODEL_MATCH_ISSUER",
        "label": "OAuth issuer base URL",
        "help": "The SDK appends /oauth2/authorize and /oauth2/token to this value. Point it at the auth base, NOT the bare host (the bare host 404s — endpoints live under /api/auth).",
        "secret": false,
        "default": "https://auth.modelmatch.com/api/auth",
        "scope": "build"
      },
      {
        "key": "VITE_MMR_API_URL",
        "label": "Model Match REST API base URL",
        "secret": false,
        "default": "https://api.modelmatch.com",
        "scope": "build"
      },
      {
        "key": "VITE_MODEL_MATCH_REDIRECT_URI",
        "label": "OAuth redirect URI",
        "help": "Must exactly match the redirect URI registered with your OAuth app.",
        "secret": false,
        "default": "http://localhost:5173/oauth/callback",
        "scope": "build"
      }
    ]
  },
  {
    "name": "Year in Review (Wrapped)",
    "slug": "wrapped",
    "description": "A Spotify-Wrapped-style year-in-review for a loan originator, by NMLS ID. Server-rendered so the API key never reaches the browser.",
    "framework": "tanstack-start",
    "auth": "api-key",
    "dir": "apps/wrapped",
    "build": {
      "publish": "dist"
    },
    "variables": [
      {
        "key": "MODEL_MATCH_API_KEY",
        "label": "Model Match API key",
        "help": "Create one in the Model Match dashboard. Sent as the x-api-key header, server-side only — it is never exposed to the browser.",
        "secret": true,
        "scope": "server"
      },
      {
        "key": "MODEL_MATCH_NMLS_ID",
        "label": "Originator NMLS ID to feature",
        "help": "The loan originator whose year gets wrapped (e.g. 1036297).",
        "secret": false,
        "scope": "server"
      },
      {
        "key": "MMR_API_URL",
        "label": "Model Match REST API base URL",
        "secret": false,
        "default": "https://api.modelmatch.com",
        "scope": "server"
      },
      {
        "key": "REPORT_YEAR",
        "label": "Year to review",
        "secret": false,
        "default": "2025",
        "scope": "server"
      }
    ]
  }
];
